---
- hosts: all
  become: yes
  tasks:
    - name: change download site
      replace:
        path: /etc/apt/sources.list
        regexp: 'http://archive.ubuntu.com/ubuntu'
        replace: 'http://ftp.jaist.ac.jp/pub/Linux/ubuntu/'
        backup: yes
    - name: install some packages
      apt:
        name:
          - aptitude
          - ubuntu-desktop
          - language-pack-ja
        update_cache: yes
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
  vars:
    rbenv:
      env: user
      version: v1.1.1
      default_ruby: 2.6.0
      rubies:
      - version: 2.6.0
        env:
          RUBY_CONFIGURE_OPTS: "--enable-shared"
    rbenv_clean_up: yes
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - vagrant
